FROM mcr.microsoft.com/devcontainers/universal:2

# Install system dependencies
RUN apt-get update && \
    apt-get install -y git wget gnupg software-properties-common && \
    apt-get install -y azure-functions-core-tools-4

